#' Table 15_26
#'
#' Hypothetical Data Set Generated by the Model Y = −1 +  3X + ε and Y* = 1 If Y > 0
#' Source: William E. Becker and Donald M. Waldman, “A Graphical Interpretation of Probit Coefficients,” Journal of Economic Education, Fall 1989, Table 1, p. 373
#'
#' @docType data
#' @usage data('Table15_26')
#' @format
#'
#' \itemize{
#' \item \strong{Y}
#' \item \strong{Y.}
#' \item \strong{X}
#' }
'Table15_26'
